### ISSUE TITLE
Cross-post to nostr and possibly butterfly app

### ISSUE THREAD

**Issue by IroncladDev** [TehcCringe/TehcCringe#70]
Would be nice

Maybe

Will consider

**Comment by ChristianPavilonis** [comment]
would be funny to take jabs at the butterfly people on their platform.

we'll see if they're good sports, but probably not.

I also think it would be funny to be on LinkedIn.

**Comment by IroncladDev** [comment]
ooh yeah linkedin might be fun

**Comment by IroncladDev** [comment]
Butterfly app is done

![image](https://github.com/user-attachments/assets/6903b20f-5b93-4ca2-868a-8a943ed9087c)
